directories:
  output: release
  buildResources: build
appId: com.ai.interview.assistant
productName: AI Interview Assistant
files:
  - filter:
      - dist/**
      - dist-electron/**
      - electron/**
      - src/**
      - package.json
mac:
  category: public.app-category.utilities
  target:
    - dmg
    - zip
  icon: assets/icons/mac/icon.icns
win:
  target:
    - nsis
    - zip
  icon: assets/icons/win/icon.ico
linux:
  target:
    - AppImage
    - deb
    - rpm
  icon: assets/icons/png/icon-256x256.png
publish:
  - provider: github
    owner: ibttf
    repo: interview-coder-frontend
electronVersion: 33.2.0
